import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV file from your local directory
sales_data = pd.read_csv('./consolidated-sales.csv')

# Calculate total revenue for each row
sales_data['Revenue'] = sales_data['Qty'] * sales_data['Amount']

# Find top 10 sold items by 'SKU'
top_selling_items = sales_data.groupby('SKU')['Qty'].sum().sort_values(ascending=False).head(10)

# Calculate revenue for each of the top 10 items
top_items_data = sales_data[sales_data['SKU'].isin(top_selling_items.index)]
revenue_per_item = top_items_data.groupby('SKU')['Revenue'].sum().sort_values(ascending=False)

# Inventory Setup
initial_inventory_per_item = 365  # Each SKU starts with 365 units
initial_inventory = {sku: initial_inventory_per_item for sku in top_selling_items.index}

# Calculate total revenue without discount
revenue_without_discount = revenue_per_item.sum()

# Apply tiered discounts
top_items_data['Discounted Price'] = top_items_data.apply(
    lambda row: row['Amount'] * (0.90 if row['Qty'] >= 2 else (0.85 if row['Qty'] >= 3 else 1)), 
    axis=1
)

# Calculate total revenue with discount
revenue_with_discount = top_items_data.groupby('SKU')['Discounted Price'].sum().sort_values(ascending=False)

# Inventory consumption calculations
def inventory_consumption(days, discount=False):
    inventory_consumed = {sku: 0 for sku in initial_inventory}
    consumption_data = {sku: [] for sku in initial_inventory}
    
    for day in range(1, days + 1):
        for sku in initial_inventory:
            if discount:
                # Assume selling a fixed number of items for discounted case
                sold_qty = min(2, initial_inventory[sku])  # 2 items sold for the sake of simplicity
            else:
                # Assume selling a fixed number of items for non-discounted case
                sold_qty = min(1, initial_inventory[sku])  # 1 item sold

            inventory_consumed[sku] += sold_qty
            initial_inventory[sku] -= sold_qty
            consumption_data[sku].append(inventory_consumed[sku])

    return consumption_data

# Simulate inventory consumption over 365 days
days = 365
consumption_without_discount = inventory_consumption(days, discount=False)
consumption_with_discount = inventory_consumption(days, discount=True)

# Visualizing Revenue
plt.figure(figsize=(12, 6))

# Bar plot for Revenue without Discount
plt.subplot(1, 2, 1)
revenue_per_item.plot(kind='bar', color='blue', alpha=0.7, label='Without Discount')
plt.title('Revenue Generated by Top Selling Items\nWithout Discount')
plt.xlabel('SKU')
plt.ylabel('Total Revenue')
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.legend()

# Bar plot for Revenue with Discount
plt.subplot(1, 2, 2)
revenue_with_discount.plot(kind='bar', color='orange', alpha=0.7, label='With Discount')
plt.title('Revenue Generated by Top Selling Items\nWith Discount')
plt.xlabel('SKU')
plt.ylabel('Total Revenue')
plt.xticks(rotation=45)
plt.grid(axis='y')
plt.legend()

plt.tight_layout()
plt.show()

# Visualizing Inventory Consumption
plt.figure(figsize=(12, 6))

# Line plot for Inventory Consumption without Discount
for sku, consumption in consumption_without_discount.items():
    plt.plot(range(1, days + 1), consumption, label=f'Without Discount - {sku}')

# Line plot for Inventory Consumption with Discount
for sku, consumption in consumption_with_discount.items():
    plt.plot(range(1, days + 1), consumption, linestyle='--', label=f'With Discount - {sku}')

plt.title('Inventory Consumption Over 365 Days')
plt.xlabel('Days')
plt.ylabel('Cumulative Inventory Consumed')
plt.legend()
plt.grid()
plt.tight_layout()
plt.show()
